import models.logistic as model_1

try:
    # training model 1
    model_1.main()
except Exception as e:
    print(e)
